-- Run in Supabase SQL editor. All private rows are protected by user_id RLS policies.
create extension if not exists "uuid-ossp";
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz default now());
create table public.subjects (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz default now(), unique(user_id,name));
create table public.syllabus_uploads (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, storage_path text not null, extracted_map jsonb, created_at timestamptz default now());
create table public.units (id uuid primary key default uuid_generate_v4(), subject_id uuid references subjects(id) on delete cascade, name text not null, position int default 0);
create table public.topics (id uuid primary key default uuid_generate_v4(), unit_id uuid references units(id) on delete cascade, name text not null, position int default 0);
create table public.subtopics (id uuid primary key default uuid_generate_v4(), topic_id uuid references topics(id) on delete cascade, name text not null);
create table public.learning_sessions (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, topic_name text, started_at timestamptz default now(), ended_at timestamptz);
create table public.notes (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, subject_name text not null, topic_name text not null, title text not null, created_at timestamptz default now(), unique(user_id,subject_name,topic_name));
create table public.note_sections (id uuid primary key default uuid_generate_v4(), note_id uuid not null references notes(id) on delete cascade, title text not null, content text not null, kind text not null default 'text', position int not null);
create table public.chat_sessions (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, topic_name text, created_at timestamptz default now());
create table public.chat_messages (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, session_id uuid not null references chat_sessions(id) on delete cascade, role text not null check(role in ('user','assistant')), content text not null, created_at timestamptz default now());
create table public.assessments (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, subject_name text not null, topic_name text not null, title text not null, difficulty text not null, created_at timestamptz default now());
create table public.assessment_questions (id uuid primary key default uuid_generate_v4(), assessment_id uuid not null references assessments(id) on delete cascade, position int not null, question text not null, type text not null, options jsonb default '[]', correct_answer text not null, explanation text not null, difficulty text not null, concept text not null);
create table public.assessment_attempts (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, assessment_id uuid not null references assessments(id) on delete cascade, score numeric not null, total_questions int not null, correct_answers int not null, completed_at timestamptz);
create table public.assessment_answers (id uuid primary key default uuid_generate_v4(), attempt_id uuid not null references assessment_attempts(id) on delete cascade, question_id uuid not null references assessment_questions(id) on delete cascade, submitted_answer text, is_correct boolean not null, concept text not null);
create table public.performance_records (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, subject_name text not null, topic_name text not null, average_score numeric not null, last_score numeric not null, attempt_count int not null default 1, updated_at timestamptz default now(), unique(user_id,topic_name));
create table public.learning_memory (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, memory_type text not null, content jsonb not null, importance smallint default 1, created_at timestamptz default now());
create table public.mentor_recommendations (id uuid primary key default uuid_generate_v4(), user_id uuid not null references auth.users(id) on delete cascade, content text not null, evidence jsonb, created_at timestamptz default now());
create table public.user_preferences (user_id uuid primary key references auth.users(id) on delete cascade, tutor_name text not null default 'AI Tutor', mentor_name text not null default 'AI Mentor', learning_style text not null default 'normal', preferred_difficulty text not null default 'adaptive');
create index on public.performance_records(user_id,average_score); create index on public.chat_messages(session_id,created_at); create index on public.notes(user_id,created_at desc);
alter table public.profiles enable row level security; alter table public.subjects enable row level security; alter table public.syllabus_uploads enable row level security; alter table public.learning_sessions enable row level security; alter table public.notes enable row level security; alter table public.chat_sessions enable row level security; alter table public.chat_messages enable row level security; alter table public.assessments enable row level security; alter table public.assessment_attempts enable row level security; alter table public.performance_records enable row level security; alter table public.learning_memory enable row level security; alter table public.mentor_recommendations enable row level security; alter table public.user_preferences enable row level security;
-- Nested entities are accessed through server API only; add equivalent ownership policies before exposing direct client reads.
do $$ declare t text; begin foreach t in array array['profiles','subjects','syllabus_uploads','learning_sessions','notes','chat_sessions','chat_messages','assessments','assessment_attempts','performance_records','learning_memory','mentor_recommendations','user_preferences'] loop execute format('create policy "own rows" on public.%I for all using (auth.uid() = %s) with check (auth.uid() = %s)',t,case when t='profiles' then 'id' else 'user_id' end,case when t='profiles' then 'id' else 'user_id' end); end loop; end $$;
insert into storage.buckets (id,name,public) values ('syllabus-images','syllabus-images',false) on conflict do nothing;
create policy "private syllabus objects" on storage.objects for all using (bucket_id='syllabus-images' and auth.uid()::text=(storage.foldername(name))[1]) with check (bucket_id='syllabus-images' and auth.uid()::text=(storage.foldername(name))[1]);
